### ISSUE TITLE
Fresh project doesn't work on OS X

### ISSUE THREAD

**Issue by ehiggs** [harshanarayana/cookiecutter-sanic#13]
**Describe the bug**

**To Reproduce**
Create a fresh project on OS X

Run the project:

```
$ python run.py       
[2019-07-25 22:16:03 +0200] [9540] [INFO] Goin' Fast @ http://0.0.0.0:8000
INFO:sanic.root:Goin' Fast @ http://0.0.0.0:8000
```

Curl the default page: 
```
$ curl http://localhost:8000
curl: (7) Failed to connect to localhost port 8000: Connection refused
```
**Expected behavior**

A working test webpage

**Environment (please complete the following information):**
 - OS: OS X
 - Version `17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64`
 - Cookiecutter Version `Cookiecutter 1.6.0 from /usr/local/Cellar/cookiecutter/1.6.0_1/libexec/lib/python3.7/site-packages (Python 3.7)

**Comment by ehiggs** [comment]
In contrast, Sanic's hello world does work:

```
$ cat run.py
from sanic import Sanic
from sanic.response import json

app = Sanic()

@app.route("/")
async def test(request):
    return json({"hello": "world"})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
```

```
$ python run.py
[2019-07-25 22:21:03 +0200] [10024] [INFO] Goin' Fast @ http://0.0.0.0:8000
[2019-07-25 22:21:03 +0200] [10024] [INFO] Starting worker [10024]
```

```
$ curl localhost:8000
{"hello":"world"}
```

**Comment by ehiggs** [comment]
Commenting out the following line allows the project to work:

```
setup_database_creation_listener(app, DATABASE)
```

**Comment by harshanarayana** [comment]
@ehiggs did you choose to enable the `orm` when creating the template if so, you have to make sure you the database is up. If you are not using the default database parameters, you will have to customize the generated skeleton accordingly. Let me add a few details on this to the readme and also provide a way to customize database params via the interactive prompt

**Comment by ehiggs** [comment]
I chose ORM and db is up. I can connect to is using sqlalchemy:

```
In [19]: engine = sqlalchemy.create_engine("postgresql://ehiggs@localhost:5432/myproject")                                                       

In [22]: engine.execute('select * from user;').fetchall()               
Out[22]: [('ehiggs',)]
```

But then using this as the SANIC_DN_DSN, it doesn't seem to work:

```
 SANIC_DB_DSN="postgresql://ehiggs@localhost:5432/myproject" python run.py
```

```
$ curl http://localhost:8000
curl: (7) Failed to connect to localhost port 8000: Connection refused
```

**Comment by harshanarayana** [comment]
@ehiggs That seems like an issue with Gino recognizing come of the ENV variables. 
xref: https://github.com/fantix/gino/blob/master/docs/sanic.rst

FYI, Current database support is enabled using Gino

Mind trying to set the DB ENV explicitly and trying it out?

**Comment by ehiggs** [comment]
Setting those variables in the code as `app.config....` worked perfectly. Thanks.

**Comment by harshanarayana** [comment]
As for the `SANIC_DN_DSN` variable, it will be parsed by `sanic` into `DB_DSN` but need to find out if Gino actually honors it. I will add some documentation around this
