### ISSUE TITLE
Generated CONTRIBUTING file doesn't template to the project name

### ISSUE THREAD

**Issue by ehiggs** [harshanarayana/cookiecutter-sanic#14]
**Describe the bug**
As a user I would like CONTRIBUTING.md to have URLs reflecting the project name and not `sanic-skeleton` so that the project is generated with my urls.

**To Reproduce**
Generate a new project.

**Expected behavior**
No reference to `sanic-skeleton` in CONTRIBUTING.md

**Environment (please complete the following information):**
NA

**Additional context**
Thanks for the cool template.

**Comment by harshanarayana** [comment]
@ehiggs When the cookiecutter template is being used it asks for values to be customized. The `sanic-skeleton` is its default name. You can override it in the interactive prompt
